apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-test
  template:
    metadata:
      labels:
        app: go-api-test
    spec:
      containers:
      - name: go-api-test
        image: go-api-test:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
