apiVersion: v1
kind: Service
metadata:
  name: go-api-test
spec:
  type: NodePort
  selector:
    app: go-api-test
  ports:
    - name: http # Add a unique name for this port
      port: 8080
      targetPort: 8080
      nodePort: 31443
